from __future__ import annotations

from .control_plane import (
    RunStatus,
    control_plane_home,
    event_stream_path,
    read_event_tail,
    run_snapshot_dir,
    sync_state,
)
from .doctor import doctor_run, doctor_summary
from .git import repo_full, repo_full_summary
from .iterm2_osc import (
    block_end,
    block_start,
    custom_button,
    cursor_shape,
    ftcs_command_executed,
    ftcs_command_finished,
    ftcs_command_start,
    ftcs_prompt,
    highlight_cursor_line,
    hyperlink,
    invalidate_buttons,
    post_notification,
    progress,
    remote_host,
    request_attention,
    set_badge,
    set_colors,
    set_current_dir,
    set_mark,
    set_profile,
    set_user_var,
    steal_focus,
    update_block,
)
from .iterm2_profiles import (
    PROFILE_SPECS,
    ProfileSpec,
    build_profiles_document,
    default_install_dir,
    hex_to_iterm2,
    install_profiles,
    serialize,
    stable_guid,
    uninstall_profiles,
)
from .runtime_paths import (
    read_version_file,
    resolve_env_path,
    vibecrafted_home,
    xdg_config_home,
)
from .workflow import (
    WorkflowLaunchSpec,
    build_launch_command,
    launch_workflow,
    normalize_launch_spec,
    vibecrafted_launcher,
)

__version__ = "0.1.0"

__all__ = [
    "PROFILE_SPECS",
    "ProfileSpec",
    "RunStatus",
    "WorkflowLaunchSpec",
    "block_end",
    "block_start",
    "build_launch_command",
    "build_profiles_document",
    "control_plane_home",
    "custom_button",
    "cursor_shape",
    "default_install_dir",
    "doctor_run",
    "doctor_summary",
    "event_stream_path",
    "ftcs_command_executed",
    "ftcs_command_finished",
    "ftcs_command_start",
    "ftcs_prompt",
    "hex_to_iterm2",
    "highlight_cursor_line",
    "hyperlink",
    "install_profiles",
    "invalidate_buttons",
    "launch_workflow",
    "normalize_launch_spec",
    "post_notification",
    "progress",
    "read_event_tail",
    "read_version_file",
    "remote_host",
    "repo_full",
    "repo_full_summary",
    "request_attention",
    "resolve_env_path",
    "run_snapshot_dir",
    "serialize",
    "set_badge",
    "set_colors",
    "set_current_dir",
    "set_mark",
    "set_profile",
    "set_user_var",
    "stable_guid",
    "steal_focus",
    "sync_state",
    "uninstall_profiles",
    "update_block",
    "vibecrafted_home",
    "vibecrafted_launcher",
    "xdg_config_home",
]
